import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Check, EyeOff, FileCheck2, KeyRound, Lock, PlusCircle, Search, ShieldCheck, Sparkles, History } from 'lucide-react';
import { PrivacyBadge } from '../components/PrivacyBadge';

const steps = [
  { num: '01', title: 'Share the concern', description: 'Choose a category and describe what happened. No account or personal profile is required.', icon: PlusCircle },
  { num: '02', title: 'Save your code', description: 'Receive a private, unpredictable case code. It is the only key you need.', icon: KeyRound },
  { num: '03', title: 'Follow the review', description: 'Use your case code to check status and read updates whenever you need.', icon: Search },
];
const pillars = [
  { icon: EyeOff, title: 'Anonymous by default', description: 'No email, phone number, or reporter account is needed.' },
  { icon: KeyRound, title: 'Private case access', description: 'Your case code gives you control without exposing identity.' },
  { icon: FileCheck2, title: 'Clear progress', description: 'See timestamped updates as your concern moves forward.' },
];

export const LandingPage: React.FC = () => (
  <div className="overflow-hidden">
    <section className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-14 pb-20 sm:pt-20 sm:pb-28">
      <div className="absolute inset-x-0 top-0 -z-10 h-[32rem] bg-[radial-gradient(ellipse_at_top,rgba(37,99,235,0.14),transparent_65%)] dark:bg-[radial-gradient(ellipse_at_top,rgba(37,99,235,0.17),transparent_65%)]" />
      <div className="grid lg:grid-cols-[1.08fr_.92fr] gap-12 lg:gap-16 items-center">
        <div className="max-w-2xl animate-fade-in">
          <div className="inline-flex items-center gap-2 rounded-full border border-brand-200/80 bg-white/75 px-3.5 py-1.5 text-xs font-bold text-brand-700 shadow-sm backdrop-blur dark:border-brand-800 dark:bg-brand-950/40 dark:text-brand-300"><Sparkles className="h-3.5 w-3.5" /> Confidential reporting, made human</div>
          <h1 className="mt-6 text-4xl font-black tracking-[-0.055em] text-slate-950 sm:text-6xl lg:text-7xl dark:text-white">Speak up.<br /><span className="text-brand-600 dark:text-brand-400">Stay protected.</span></h1>
          <p className="mt-6 max-w-xl text-base leading-8 text-slate-600 sm:text-lg dark:text-slate-300">WhistleDrop gives you a simple, safe way to report concerns and follow what happens next — without creating an account or revealing who you are.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/submit" className="inline-flex items-center justify-center gap-2 rounded-xl bg-brand-600 px-6 py-3.5 text-sm font-bold text-white shadow-lg shadow-brand-600/25 transition hover:-translate-y-0.5 hover:bg-brand-700"><PlusCircle className="h-5 w-5" /> Report a concern <ArrowRight className="h-4 w-4" /></Link><Link to="/track" className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white/80 px-6 py-3.5 text-sm font-bold text-slate-700 shadow-sm transition hover:border-slate-300 hover:bg-white dark:border-slate-700 dark:bg-slate-900/70 dark:text-slate-200"><Search className="h-5 w-5 text-brand-600" /> Track a report</Link></div>
          <div className="mt-7 flex flex-wrap gap-x-5 gap-y-3 text-sm font-medium text-slate-600 dark:text-slate-300"><span className="inline-flex items-center gap-2"><Lock className="h-4 w-4 text-brand-600" /> No account required</span><span className="inline-flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-brand-600" /> Identity not collected</span></div>
        </div>
        <div className="relative mx-auto w-full max-w-md lg:max-w-none animate-slide-up"><div className="absolute -inset-5 rounded-[2rem] bg-brand-400/15 blur-3xl" /><div className="relative rounded-3xl border border-white/80 bg-white/90 p-5 shadow-2xl shadow-slate-900/10 backdrop-blur dark:border-slate-700 dark:bg-slate-900/90 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-600 dark:text-brand-400">Your private path</p><h2 className="mt-2 text-xl font-extrabold text-slate-900 dark:text-white">Protected at every step</h2></div><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-brand-100 text-brand-700 dark:bg-brand-950 dark:text-brand-300"><ShieldCheck className="h-6 w-6" /></div></div><div className="mt-7 space-y-4">{['Share only what matters', 'Keep your unique case code', 'Check for updates anytime'].map((item, index) => <div key={item} className="flex items-center gap-3 rounded-2xl border border-slate-100 bg-slate-50/80 p-3.5 dark:border-slate-800 dark:bg-slate-950/50"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-brand-600 text-xs font-black text-white">{index + 1}</span><span className="text-sm font-semibold text-slate-700 dark:text-slate-200">{item}</span><Check className="ml-auto h-4 w-4 text-brand-600" /></div>)}</div><div className="mt-6 rounded-2xl bg-slate-900 p-4 text-slate-100 dark:bg-slate-800"><div className="flex items-center gap-2 text-xs font-bold text-brand-300"><History className="h-4 w-4" /> CASE STATUS</div><div className="mt-2 flex items-center justify-between"><span className="font-mono text-sm tracking-wider">WD-••••••••</span><span className="rounded-full bg-brand-500/20 px-2.5 py-1 text-xs font-bold text-brand-300">Private</span></div></div></div></div>
      </div>
    </section>
    <section className="border-y border-slate-200/80 bg-white/65 py-16 dark:border-slate-800 dark:bg-slate-900/30 sm:py-20"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-600 dark:text-brand-400">Simple by design</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-900 sm:text-4xl dark:text-white">A clear route from concern to progress.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{steps.map((step) => { const Icon = step.icon; return <div key={step.num} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-brand-200 hover:shadow-lg hover:shadow-brand-600/5 dark:border-slate-800 dark:bg-slate-900 dark:hover:border-brand-800"><div className="flex items-center justify-between"><span className="font-mono text-sm font-bold text-brand-600 dark:text-brand-400">{step.num}</span><div className="rounded-xl bg-brand-50 p-2.5 text-brand-700 transition group-hover:bg-brand-600 group-hover:text-white dark:bg-brand-950 dark:text-brand-300"><Icon className="h-5 w-5" /></div></div><h3 className="mt-8 text-lg font-extrabold text-slate-900 dark:text-white">{step.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">{step.description}</p></div>; })}</div></div></section>
    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24"><div className="rounded-3xl bg-slate-950 px-6 py-10 text-white shadow-xl sm:px-10 sm:py-14 lg:px-14"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-400">Built around privacy</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Your identity should never be the cost of speaking up.</h2><p className="mt-4 text-sm leading-7 text-slate-300 sm:text-base">We minimize data from the start, so you can concentrate on the concern — not on creating a profile or protecting personal information.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{pillars.map((pillar) => { const Icon = pillar.icon; return <div key={pillar.title} className="rounded-2xl border border-white/10 bg-white/5 p-5"><Icon className="h-5 w-5 text-brand-400" /><h3 className="mt-4 font-bold">{pillar.title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{pillar.description}</p></div>; })}</div><div className="mt-9 flex flex-wrap gap-2"><PrivacyBadge variant="anonymous" /><PrivacyBadge variant="no-account" /><PrivacyBadge variant="key-based" /></div></div></section>
  </div>
);
